"""Add Phase 2 durable runtime models

Revision ID: ba79da6588fd
Revises: pfmm70_20260721
Create Date: 2026-07-22 20:20:54.213097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba79da6588fd'
down_revision: Union[str, None] = 'pfmm70_20260721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_work_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_work_item_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=36), nullable=True),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_work_items_original_work_item_id'), 'failed_work_items', ['original_work_item_id'], unique=False)
    op.create_index(op.f('ix_failed_work_items_pipeline_run_id'), 'failed_work_items', ['pipeline_run_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('play_code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_play_code'), 'pipeline_runs', ['play_code'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('source_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=80), nullable=False),
    sa.Column('high_water_mark', sa.String(length=200), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_checkpoints_source_name'), 'source_checkpoints', ['source_name'], unique=True)
    op.create_table('source_rate_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=80), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('used_today', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_rate_budgets_source_name'), 'source_rate_budgets', ['source_name'], unique=True)
    op.create_table('work_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=36), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('lock_lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_items_pipeline_run_id'), 'work_items', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_work_items_status'), 'work_items', ['status'], unique=False)
    op.create_index(op.f('ix_work_items_task_name'), 'work_items', ['task_name'], unique=False)
    op.alter_column('campaigns', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('companies', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('companies', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_classifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_domains', 'first_seen_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_estimates', 'observed_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_identifiers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_locations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_names', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('compliance_decisions', 'evaluated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('compliance_policies', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('evidence_items', 'observed_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('evidence_signals', 'prospect_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('evidence_signals', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('evidence_signals', 'signal_type',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('evidence_signals', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('evidence_signals', 'evidence_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('evidence_signals', 'confidence',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'50'"))
    op.alter_column('evidence_signals', 'strength',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'50'"))
    op.alter_column('evidence_signals', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('evidence_signals', 'manually_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('evidence_signals', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_evidence_signals_category'), 'evidence_signals', ['category'], unique=False)
    op.create_index(op.f('ix_evidence_signals_signal_type'), 'evidence_signals', ['signal_type'], unique=False)
    op.alter_column('ingestion_runs', 'adapter',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('ingestion_runs', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'running'"))
    op.alter_column('ingestion_runs', 'started_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_ingestion_runs_adapter'), 'ingestion_runs', ['adapter'], unique=False)
    op.alter_column('market_play_versions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('market_plays', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('market_plays', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('market_plays', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('offer_assets', 'asset_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('offer_assets', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('offer_assets', 'url_or_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('offer_assets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.create_index(op.f('ix_offer_assets_market_play_code'), 'offer_assets', ['market_play_code'], unique=False)
    op.alter_column('opportunities', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('opportunities', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('outreach_events', 'event_date',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('outreach_events', 'event_kind',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('outreach_events', 'pipeline_stage_after',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('people', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('person_roles', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('prospects', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('prospects', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('qualification_reviews', 'prospect_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('qualification_reviews', 'decision',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('qualification_reviews', 'fit_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'pain_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'trigger_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'buyer_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'contact_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'offer_match_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_qualification_reviews_prospect_id'), 'qualification_reviews', ['prospect_id'], unique=False)
    op.alter_column('score_snapshots', 'computed_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('source_connectors', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('source_records', 'retrieved_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('source_runs', 'started_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('suppression_entries', 'kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('suppression_entries', 'value_normalized',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.alter_column('suppression_entries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_suppression_entries_kind'), 'suppression_entries', ['kind'], unique=False)
    op.create_index(op.f('ix_suppression_entries_value_normalized'), 'suppression_entries', ['value_normalized'], unique=False)
    op.alter_column('tasks', 'prospect_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'50'"))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'open'"))
    op.alter_column('tasks', 'origin',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'manual'"))
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_prospect_id'), 'tasks', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.alter_column('touches', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('touches', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_prospect_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('tasks', 'origin',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'manual'"))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'open'"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'50'"))
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('tasks', 'prospect_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_suppression_entries_value_normalized'), table_name='suppression_entries')
    op.drop_index(op.f('ix_suppression_entries_kind'), table_name='suppression_entries')
    op.alter_column('suppression_entries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('suppression_entries', 'value_normalized',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.alter_column('suppression_entries', 'kind',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('source_runs', 'started_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('source_records', 'retrieved_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('source_connectors', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('score_snapshots', 'computed_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_qualification_reviews_prospect_id'), table_name='qualification_reviews')
    op.alter_column('qualification_reviews', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('qualification_reviews', 'offer_match_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'contact_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'buyer_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'trigger_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'pain_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'fit_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qualification_reviews', 'decision',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('qualification_reviews', 'prospect_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prospects', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('prospects', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('person_roles', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('people', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('outreach_events', 'pipeline_stage_after',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('outreach_events', 'event_kind',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('outreach_events', 'event_date',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('opportunities', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('opportunities', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_offer_assets_market_play_code'), table_name='offer_assets')
    op.alter_column('offer_assets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('offer_assets', 'url_or_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('offer_assets', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('offer_assets', 'asset_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('market_plays', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('market_plays', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('market_plays', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('market_play_versions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_ingestion_runs_adapter'), table_name='ingestion_runs')
    op.alter_column('ingestion_runs', 'started_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ingestion_runs', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'running'"))
    op.alter_column('ingestion_runs', 'adapter',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_index(op.f('ix_evidence_signals_signal_type'), table_name='evidence_signals')
    op.drop_index(op.f('ix_evidence_signals_category'), table_name='evidence_signals')
    op.alter_column('evidence_signals', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('evidence_signals', 'manually_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('evidence_signals', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('evidence_signals', 'strength',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'50'"))
    op.alter_column('evidence_signals', 'confidence',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'50'"))
    op.alter_column('evidence_signals', 'evidence_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('evidence_signals', 'label',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('evidence_signals', 'signal_type',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('evidence_signals', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('evidence_signals', 'prospect_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evidence_items', 'observed_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('compliance_policies', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('compliance_decisions', 'evaluated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_names', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_locations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_identifiers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_estimates', 'observed_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_domains', 'first_seen_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('company_classifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('companies', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('companies', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('campaigns', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_work_items_task_name'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_status'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_pipeline_run_id'), table_name='work_items')
    op.drop_table('work_items')
    op.drop_index(op.f('ix_source_rate_budgets_source_name'), table_name='source_rate_budgets')
    op.drop_table('source_rate_budgets')
    op.drop_index(op.f('ix_source_checkpoints_source_name'), table_name='source_checkpoints')
    op.drop_table('source_checkpoints')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_play_code'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_failed_work_items_pipeline_run_id'), table_name='failed_work_items')
    op.drop_index(op.f('ix_failed_work_items_original_work_item_id'), table_name='failed_work_items')
    op.drop_table('failed_work_items')
    # ### end Alembic commands ###
